version: "3.9"

services:
  # auth:
  #   build:
  #     dockerfile: deploy/auth/Dockerfile_Debug
  #   ports:
  #     - "40001:40000"
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined

  # config:
  #   build:
  #     dockerfile: deploy/config/Dockerfile_Debug
  #   ports:
  #     - "40002:40000"
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined

  # queue:
  #   build:
  #     dockerfile: deploy/queue/Dockerfile_Debug
  #   ports:
  #     - "40003:40000"
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined

  request:
    build:
      dockerfile: deploy/request/Dockerfile_Debug
    ports:
      - "40004:40000"
    volumes:
      - ./backend:/app
    environment:
      - RUN_MODE=air
      - CGO_ENABLED=0
      - GO111MODULE=on
    working_dir: /app

  # gateway:
  #   build:
  #     dockerfile: deploy/gateway/Dockerfile_Debug
  #   ports:
  #     - "40005:40000"
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined
