FROM golang:1.24-alpine as builder

# Установка необходимых пакетов
RUN apk update && apk add --no-cache \
    git \
    curl \
    unzip \
    protobuf \
    make

# Установка Go-плагинов для protobuf
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Работаем в директории приложения
WORKDIR /app

# Копируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем остальное
COPY . .

# Генерация protobuf
RUN make proto



CMD ["air", "-c", "deploy/gateway/air.toml"]
