root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/auth_service ./cmd/auth/main.go && chmod +x ./tmp/auth_service"
  bin = "./tmp/auth_service"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  log = "build.log"
