syntax = "proto3";

package account;

import "google/protobuf/empty.proto";

option go_package = "generated/proto/account;account";

message Account {
  int32 Id = 1;
  string Nickname = 2;
  string Email = 3;
  string UserId = 4;
}

message AddAccountRequest {
  string Nickname = 1;
  string Email = 2;
  int32 UserId = 3;
}

message GetAccountRequest { string Nickname = 1; }

message ListAccountRequest { int32 UserId = 1; }

message DeleteAccountRequest { int32 Id = 1; }

message ListAccountResponse { repeated Account Accounts = 1; }

service AccountService {
  rpc AddAccount(AddAccountRequest) returns (Account);
  rpc GetAccount(GetAccountRequest) returns (Account);
  rpc ListAccount(ListAccountRequest) returns (ListAccountResponse);
  rpc DeleteAccount(DeleteAccountRequest) returns (google.protobuf.Empty);
}