syntax = "proto3";

package article;

import "google/protobuf/empty.proto";
import "account.proto";

option go_package = "generated/proto/article;article";

message AddArticleRequest {
  string title = 1;
  string content = 2;
  repeated string tags = 3;
  account.Account author = 4;
}

message ListArticlesRequest { account.Account requester = 1; }

message ListArticlesResponse { repeated Article articles = 1; }

message Article {
  int32 id = 1;
  string title = 2;
  string content = 3;
  repeated string tags = 4;
  account.Account author = 5;
}

service ArticleService {
  rpc AddArticle(AddArticleRequest) returns (google.protobuf.Empty);
  rpc ListArticles(ListArticlesRequest) returns (ListArticlesResponse);
}
