syntax="proto3";


package config;

option go_package = "generated/proto/config;configPb";

message addConfigRequest {
    string name = 1;
    int64 userId = 2;
    string prompt = 3;
    string refreshTokenDTF = 4;
    int64 delay = 5;
    string email = 6;
    string password = 7;
    string refreshTokenVC = 8;
}

message Config {
    string Id = 1;
    int64 userId = 2;
    string name = 3;
    string prompt = 4;
    string refreshTokenDTF = 5;
    string email = 6;
    string password = 7;
    int64 delay = 8;
    string refreshTokenVC = 9;
}

message getConfigsRequest{
    int64 userId = 1;
}
message getConfigRequest {
    string configId = 1;
}

message Configs {
    repeated Config Configs = 1;
}
message deleteConfigRequest {
    string Id = 1;
    int64 userId = 2;
}
message updateRefreshTokenDTFRequest {
    string refreshTokenDTF = 1;
    string id = 2;
}
message updateRefreshTokenVCRequest {
    string refreshTokenVC = 1;
    string id = 2;
}

message Empty {}

service ConfigService {
    rpc AddConfig(addConfigRequest) returns (Config);
    rpc DeleteConfig(deleteConfigRequest) returns (Empty);
    rpc GetConfigs(getConfigsRequest) returns (Configs);
    rpc GetConfig(getConfigRequest) returns (Config);
    rpc UpdateRefreshDTFToken(updateRefreshTokenDTFRequest) returns (Empty);
    rpc UpdateRefreshVCToken(updateRefreshTokenVCRequest) returns (Empty);
}