syntax = "proto3";

package partner;

import "google/protobuf/empty.proto";

option go_package = "generated/proto/partner;partnerpb";

message Partner {
  int32  Id    = 1;
  string Token = 2;
  string Name  = 3;
}

message ListPartnersRequest  { }
message ListPartnersResponse { repeated Partner Partners = 1; }


message ViewPartnerRequest  { int32 id = 1; }
message ViewPartnerResponse { Partner Partner = 1; }

message AddPartnerRequest { 
	string Token = 1;
	string Name = 2;
}


message DeletePartnerRequest { int32 id = 1; }

service PartnerService {
  rpc ViewPartner    (ViewPartnerRequest)    returns (ViewPartnerResponse);
  rpc ListPartners   (ListPartnersRequest)   returns (ListPartnersResponse);
  rpc AddPartner     (AddPartnerRequest)     returns (google.protobuf.Empty);
  rpc DeletePartner  (DeletePartnerRequest)  returns (google.protobuf.Empty);
}
