syntax = "proto3";

package prompt;

import "google/protobuf/empty.proto";

option go_package = "generated/proto/prompt;promptpb";

message Prompt {
  int32 Id     = 1;
  string Text  = 2;
  int32 Theme  = 3;
  string Name  = 4;
}

message ListPromptsRequest {}
message ListPromptsResponse { repeated Prompt Prompts = 1; }

message ViewPromptRequest { int32 Id = 1; }
message ViewPromptResponse { Prompt Prompt = 1; }

message AddPromptRequest { Prompt Prompt = 1; }
message DeletePromptRequest { int32 Id = 1; }

service PromptService {
  rpc ViewPrompt(ViewPromptRequest) returns (ViewPromptResponse);
  rpc ListPrompts(ListPromptsRequest) returns (ListPromptsResponse);
  rpc AddPrompt(AddPromptRequest) returns (google.protobuf.Empty);
  rpc DeletePrompt(DeletePromptRequest) returns (google.protobuf.Empty);
}
