syntax = "proto3";

package queue;

option go_package = "generated/proto/queue;queuepb";

message Article {
  string Title = 2;
  repeated Block Blocks = 3;
}

message Block {
  string Type = 1;
  BlockData Data = 2;
}
message BlockData {
  string Text = 1;
  string Lang = 2;
  repeated string Items = 3;
  string Type = 4;
}


message ListQueueRequest { int64 UserId = 1; }

message ListQueueResponse { repeated Article Articles = 1; }

service QueueService {
  rpc ListQueue(ListQueueRequest) returns (ListQueueResponse);
}
