syntax = "proto3";

package request;

option go_package = "generated/proto/request;request";

// Send Article
enum WebSite {
  DTF = 0;
  VC_RU = 1;
}
message sendArticleRequest {
  WebSite WebSite = 1;
  EntryRequest Entry = 2;
  string ConfigId = 3;
}
message EntryRequest {
  int64 id = 1;
  int64 user_id = 2;
  int64 subsite_id = 3;
  int32 type = 4;
  string title = 5;
  Entry entry = 6;
}
message Entry { repeated Block blocks = 1; }

message Block {
  string type = 1;
  bool cover = 2;
  bool hidden = 3;
  string anchor = 4;
  BlockData data = 5;
}

message BlockData {
  // для media
  repeated MediaItem items = 1;

  // общий
  string type = 2;

  // для text, code, header, quote
  string text = 3;

  // для header
  string style = 4;

  // для quote
  string subline1 = 5;
  string subline2 = 6;
  ImageItem image = 7;

  // для code
  string lang = 8;
}

message MediaItem {
  string title = 1;
  ImageItem image = 2;
}

message ImageItem {
  string render = 1;
  string type = 2;
  ImageData data = 3;
}

message ImageData {
  string uuid = 1;
  int32 width = 2;
  int32 height = 3;
  int32 size = 4;
  string type = 5;
  string color = 6;
  string hash = 7;
  repeated string external_service = 8;
  string base64preview = 9;
  bool isVideo = 10;
  int32 duration = 11;
  bool has_audio = 12;
}

message uploadMediaRequest {
  WebSite WebSite = 1;
  string urlFile = 2;
}
message uploadMediaResponse { ImageItem info = 1; }

message uploadResponse {
  string message = 1;
  repeated ImageItem result = 2;
}
// Generate Text
message generateTextRequest {
  string prompt = 1;
  string link = 2;
}
message Text {
  string Title = 1;
  repeated Block Blocks = 2;
}
// Get Refresh Tokens
message getRefreshTokenRequest {
  string email = 1;
  string password = 2;
}
message getRefreshTokenResponse { string refreshToken = 1; }
// Get Item Link
message getItemLinkRequest {
  string URI = 1;
  WebSite WebSite = 2;
}
message ItemLink {
  string URI = 1;
  string ShortURI = 2;
}
// Other
message Empty {}

service RequestService {
  rpc SendArticle(sendArticleRequest) returns (Empty);
  rpc UploadMedia(uploadMediaRequest) returns (uploadMediaResponse);
  rpc GenerateText(generateTextRequest) returns (Text);
  rpc GetItemLink(getItemLinkRequest) returns (ItemLink);
  rpc GetRefreshTokenDTF(getRefreshTokenRequest)
      returns (getRefreshTokenResponse);
  rpc GetRefreshTokenVC(getRefreshTokenRequest)
      returns (getRefreshTokenResponse);
}