syntax = "proto3";

package statistics;
import "google/protobuf/timestamp.proto";
option go_package = "generated/proto/statistics;statistics";




message ArticleEvent {
  int64 article_id = 1;
  int64 user_id = 2;
  google.protobuf.Timestamp event_time = 3;
}
message EventBatch {
  repeated ArticleEvent events = 1;
}
message GetEventRequest {
    int64 user_id = 1;
}
message Empty {}

service StatisticsService {
  rpc WriteEvents(EventBatch) returns (Empty);
  rpc GetEvents(GetEventRequest) returns (ArticleEvent);
}