syntax = "proto3";

package theme;

import "google/protobuf/empty.proto";

option go_package = "generated/proto/theme;themepb";

message Theme {
  int32 Id          = 1;
  string Category   = 2;
  string Name       = 3;
  string Description = 4;
}

message ListThemesRequest {
  int32 UserId = 1;
}
message ListThemesResponse { repeated Theme Themes = 1; }

message ViewThemeRequest { int32 Id = 1; }
message ViewThemeResponse { Theme Theme = 1; }

message AddThemeRequest { 
  string Category = 1;
  string Name = 2;
  string Description = 3;
 }

message DeleteThemeRequest { int32 Id = 1; }

service ThemeService {
  rpc ViewTheme(ViewThemeRequest) returns (ViewThemeResponse);
  rpc ListThemes(ListThemesRequest) returns (ListThemesResponse);
  rpc AddTheme(AddThemeRequest) returns (google.protobuf.Empty);
  rpc DeleteTheme(DeleteThemeRequest) returns (google.protobuf.Empty);
}
