const SETTINGS_ROUTE = "/settings"
const DASHBOARD_ROUTE = "/dashboard"
const LOGIN_ROUTE = "/login"
const REGISTER_ROUTE = "/register"
const THEMES_ROUTE = "/themes"
const PROMPTS_ROUTE = "/prompts"
const ADD_ARTICLE_ROUTE = "/add-article"
const QUEUE_ROUTE = "/queue"
